### ISSUE TITLE
Quiver is not metal armor

### ISSUE THREAD

**Issue by Broam** [AnodeCathode/TechNodeFirmaCraft#15]
Putting on a quiver will cause a player to crash, and repeatedly crash immediately upon login.

[20/9/2020 16:45:55 PM] [16:45:55] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Pre@79cd43ca:
[20/9/2020 16:45:55 PM] java.lang.ClassCastException: net.dries007.tfc.objects.items.ItemQuiver cannot be cast to net.dries007.tfc.objects.items.metal.ItemMetalArmor
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.modifiers.EquipmentModifier.getModifiers(EquipmentModifier.java:37) ~[EquipmentModifier.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.capability.TemperatureSystem.evaluateModifiers(TemperatureSystem.java:69) ~[TemperatureSystem.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.capability.TemperatureSystem.<init>(TemperatureSystem.java:57) ~[TemperatureSystem.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.capability.TemperatureSystem.getTemperatureFor(TemperatureSystem.java:187) ~[TemperatureSystem.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.capability.TemperatureCapability.getCapability(TemperatureCapability.java:34) ~[TemperatureCapability.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108) ~[CapabilityDispatcher.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.entity.Entity.getCapability(Entity.java:3121) ~[vg.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.entity.EntityLivingBase.getCapability(EntityLivingBase.java:2960) ~[vp.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.entity.player.EntityPlayer.getCapability(EntityPlayer.java:2682) ~[aed.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.GuiRenderer.drawTemperatureVignettes(GuiRenderer.java:181) ~[GuiRenderer.class:?]
[20/9/2020 16:45:56 PM] 	at com.lumintorious.ambiental.GuiRenderer.render(GuiRenderer.java:83) ~[GuiRenderer.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1013_GuiRenderer_render_Pre.invoke(.dynamic) ~[?:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907) [GuiIngameForge.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:119) [GuiIngameForge.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098) [buq.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[20/9/2020 16:45:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
[20/9/2020 16:45:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
[20/9/2020 16:45:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
[20/9/2020 16:45:56 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
[20/9/2020 16:45:56 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[20/9/2020 16:45:56 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by AnodeCathode** [comment]
Fixed in 12.2.30
