### ISSUE TITLE
Mining Drill crashes server

### ISSUE THREAD

**Issue by AnodeCathode** [AnodeCathode/TechNodeFirmaCraft#18]
Time: 2020-09-26 01:08:44 MDT
Description: Ticking player

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=can_fall, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=tfc:cobble/andesite, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at net.dries007.tfc.objects.blocks.stone.BlockRockRaw.getMetaFromState(BlockRockRaw.java:63)
    at net.minecraft.block.Block.getHarvestTool(Block.java:2057)
    at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:226)
    at net.minecraft.block.Block.canHarvestBlock(Block.java:1154)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:316)
    at net.minecraft.server.management.PlayerInteractionManager.updateBlockRemoving(PlayerInteractionManager.java:109)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:316)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642)
    at net.minecraft.world.World.updateEntities(World.java:1737)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by AnodeCathode** [comment]
PR into TFC to fix. It's a hack but appears to work on the server.

**Comment by AnodeCathode** [comment]
Finally fixed in 12.2.51
