### ISSUE TITLE
Crash when breaking fruit tree branch

### ISSUE THREAD

**Issue by AnodeCathode** [AnodeCathode/TechNodeFirmaCraft#40]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-10-19 19:01:57 MDT
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=state, clazz=class net.dries007.tfc.objects.blocks.agriculture.BlockFruitTreeLeaves$EnumLeafState, values=[NORMAL, FLOWERING, FRUIT]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at net.dries007.tfc.objects.blocks.agriculture.BlockFruitTreeLeaves.TickCentral_TrueRandomTick(BlockFruitTreeLeaves.java:113)
    at com.github.terminatornl.tickcentral.api.TickHub.trueRandomTick(TickHub.java:28)
    at com.github.terminatornl.laggoggles.Main.redirectRandomTick(Main.java:78)
    at net.dries007.tfc.objects.blocks.agriculture.BlockFruitTreeLeaves.randomTick(BlockFruitTreeLeaves.java)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: world
  All players: 4 total; [EntityPlayerMP['xxxxxx'/344, l='world', x=-491.26, y=144.00, z=1936.12], EntityPlayerMP['xxxxxx'/4733, l='world', x=-1082.01, y=149.00, z=929.94], EntityPlayerMP['xxxxx'/15585, l='world', x=-519.70, y=144.00, z=1956.32], EntityPlayerMP['xxxxxx'/78667, l='world', x=-1729.33, y=150.00, z=675.65]]
  Chunk stats: ServerChunkCache: 1379 Drop: 0
  Level seed: xxxxxxx
  Level generator: ID 09 - tfc_classic, ver 0. Features enabled: true
  Level generator options: {"spawnFuzz":250,"flatBedrock":false,"ravineRarity":100,"ravineHeight":20,"ravineVariability":50,"surfaceRavineRarity":100,"surfaceRavineHeight":125,"surfaceRavineVariability":30,"riverRavineRarity":400,"lavaFissureRarity":25,"waterFissureRarity":90,"lavaFissureClusterRarity":400,"waterFissureClusterRarity":225,"largeRockRarity":20,"fixSortRocks":true}
  Level spawn location: World: (-907,151,-997), Chunk: (at 5,9,11 in -57,-63; contains blocks -912,0,-1008 to -897,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
  Level time: 92328771 game time, 73378777 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 3875 (now: true), thunder time: 151396 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by AnodeCathode** [comment]
Pulled TickCentral and LagGoggles out to ensure they were not doing some thing odd. So this is without those in the stack

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020-10-20 22:48:46 MDT
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=state, clazz=class net.dries007.tfc.objects.blocks.agriculture.BlockFruitTreeLeaves$EnumLeafState, values=[NORMAL, FLOWERING, FRUIT]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
at net.dries007.tfc.objects.blocks.agriculture.BlockFruitTreeLeaves.randomTick(BlockFruitTreeLeaves.java:120)
at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476)
at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)

**Comment by AnodeCathode** [comment]
Submitted as issue to TFC: https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1609

Submitted PR to fix issue: https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/1613
