### ISSUE TITLE
Game crashes when breaking andesite stairs

### ISSUE THREAD

**Issue by 4emili4** [AnodeCathode/TechNodeFirmaCraft#6]
Hello, 

The issue is able to be recreated and the Log file is here: https://paste.atlauncher.com/view/90682beb

Line 5885 is where I log in and immediately break the other stair for testing. Line 5939 is where things go sideways. 

Server logs are this: 

[21:04:34] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Taqiri[/192.168.1.4:54491] logged in with entity id 3712366 at (173.4446183384855, 150.0, 284.1017449858409)
[21:04:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Taqiri joined the game
[21:04:34] [Server thread/INFO] [Waila]: Player EntityPlayerMP['Taqiri'/3712366, l='TechWorld', x=173.44, y=150.00, z=284.10] connected. Sending ping
[21:04:34] [Server thread/INFO] [tfc]: Player Logged In - Checking for Calendar Updates.
[21:04:34] [Server thread/INFO] [tfc]: Reverted doDaylightCycle to true as players are logged in.
[21:04:52] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=can_fall, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=tfc:stairs/smooth/andesite, properties=[facing, half, shape]}
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=can_fall, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=tfc:stairs/smooth/andesite, properties=[facing, half, shape]}

**Comment by AnodeCathode** [comment]
Should be fixed in latest TNFC and TFC update.
