### ISSUE TITLE
Add note: Don't break RH machines while connected to running RH machines

### ISSUE THREAD

**Issue by AnodeCathode** [AnodeCathode/TechNodeFirmaCraft#87]
Duh!

Time: 2020-11-09 12:38:39 MST
Description: Ticking block entity

java.lang.NullPointerException
    at com.globbypotato.rockhounding_chemistry.machines.tile.TEMetalAlloyer.process(TEMetalAlloyer.java:327)
    at com.globbypotato.rockhounding_chemistry.machines.tile.TEMetalAlloyer.TickCentral_TrueITickableUpdate(TEMetalAlloyer.java:282)

**Comment by AnodeCathode** [comment]
Fixed 12.2.51
